platform :ios, '14.0'
inhibit_all_warnings!

source 'https://github.com/CocoaPods/Specs.git'

target 'Demo' do
  use_frameworks!
  
  pod 'AudioPlayer', :path => "../"
  pod 'SnapKit' , '~>5.0.0'
  pod 'UIAdapter'
  pod 'Loading', '~>1.1.0'
  pod 'UIImageColors'
  pod 'Kingfisher', '~> 7.0'
  pod

end

target 'Demo Watch WatchKit Extension' do
  platform :watchos, '8.0'
  
  pod 'AudioPlayer', :path => "../"
  
end
